### ISSUE TITLE
Unneeded Microsoft.AspNetCore.Owin dependency

### ISSUE THREAD

**Issue by klettier** [sbebrys/ZipkinTracer#9]
Hello, 

Came across your repo with the expectation to find an Owin Middleware integrated with dotnet core because you have a dependency to ``Microsoft.AspNetCore.Owin`` but it seems that dep isn't used at all. 

Do you plan to do something with it ? 

Regards, 

Kevin

**Comment by klettier** [comment]
Btw I'm interested by a zipkin package for Owin and Dotnet core

**Comment by sbebrys** [comment]
Hi, You have right `Microsoft.AspNetCore.Owin` is not needed. I remove it and make update others refs. This package You can use in .Net Core and standard AspNetCore hosting MS - `Microsoft.AspNetCore.Hosting` with owin implementation server (Kestrel). I do it the same in multiplatform deployment (WinServer and Debian).
